version: '3.7'

services:
  backend:
    container_name: blog-admin
    hostname: blog-backend
    image: klimenkov/shadowic-blog-admin
    restart: always
    ports:
      - "9501:1337"
    depends_on:
      - db
    env_file: shadow_blog_admin.env

  db:
    image: mysql:8.0.30
    restart: always
    ports:
      - "3306:3306"
    env_file: shadow_blog_admin.env
    volumes:
      - ./pg-data:/var/lib/mysql/data

volumes:
  pg_data:

#  frontend:
#    container_name: blog-front
#    hostname: blog-frontend
#    image: klimenkov/shadowic-blog-frontend
#    ports:
#      - "9502:3000"
#    env_file: shadow_blog_front.env

networks:
  default:
    external:
      name: database
